apiVersion: v1
kind: Secret
metadata:
    name: prometheus-secrets
    namespace: observability
stringData:
    SECRET_PUSHOVER_API_KEY: ENC[AES256_GCM,data:BulwkEKEE+AgdQIHP6/Ov6pz1eA/4FOi9ySFnbl/,iv:2LuRMbp/LpgJC0SDBW2FixWdtgKVjsELxuaTQrz6n2M=,tag:rDnGCSodS/M73Ksye9XfSw==,type:str]
    SECRET_PUSHOVER_USER_KEY: ENC[AES256_GCM,data:siCCw7/ihEttNZrCMNC5b20DNzj/nJsduGoXU/nE,iv:KFYEiKgjj6iIbxlfIwpHKdMo7MbQn2WoY7vceLwCGQM=,tag:uyxIiVAbkvduNgN+o09GIA==,type:str]
    MINIO_BAREAR_TOKEN: ENC[AES256_GCM,data:UdlJyIYvOl8wRXE7zt8Oi1hs8qKbsoenqjcOTjkHl7nrlOCwgpM3Le5bV3PYMVbiTsXUxdesBTazsmqp1Al+j5KJhgiAoYSDla6qfuk6SjYJCxO+vas3rlGl6GR3SK11yJVFdbPr/2SrQn0Gy1epnW55jin9IUje0qfqikRsZaFWXLpgF0EW7Pi4yqHCxgZShW1E0BI5pyD+mXEbq99YbXaPV+3gLKQYuKcggxl2,iv:rRMAz1Q16q0z3olxvcSXOQ7/Y7XY34TGax30MKZy/qQ=,tag:+B9zeFGOkKbqg/sEDVluTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmnhp30e40u4q54znn8ysz3atvee5k4q9r585y8mzxz9xuuxm37spk5w4w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTzIxYVBDa0Z5MnE5MWFp
            SXR0TjhDdFB4SkJySCsxT0p2MWhvbmxxRWlZCk5oTWo4ZGg5UTljTVAzSVNBSjVw
            WVg5djJiQlo4THZQTGd1eDZqUVdKVVkKLS0tIEdVSWFlMTFpaWo3QTJ1QVdiQ0xm
            Wk5KMGc1aUVGQ0FZZXFFdHJCTzJOblUKXBs9Mj3Ci86piqWVM+ARROyQWW6E8Int
            60sLRWLziDKOO3u6UyXOl+YGgOn5958cxUocsJJ9BLT4RpdslBYUIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-22T21:36:15Z"
    mac: ENC[AES256_GCM,data:bCkE4DAC8fBmF/HJG9/HzDyigSjbt5nHARFyypjyrxQlUEKu3cIXW1QmUTVhLZME/Z1wKNfqCSgrRLZhjzzgEAn0lHRJZYt2o49zevveMOoXMY9PpkwMkz7QazWn+FQc0fdLMMpY00UG2KjcYcRpJmWHOg7rBG9Ub9qlGil1X2Y=,iv:3H510Ele3An9+/zbhj9QZYg/7Y20kVGtrn69aFxZJJc=,tag:EEDAolZbWhv1PUITafnd+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
