---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./backube.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./democratic-csi.yaml
  - ./emberstack.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./intel.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./nextcloud.yaml
  - ./node-feature-discovery-charts.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./postfinance.yaml
  - ./prometheus-community.yaml
  - ./rook-ceph.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
