apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:lJip9noVISGIDxk=,iv:pztNuVKBuSyS8jxTfMVlpFDdpwGoUAWFczGw88aG+rI=,tag:OGeJ5qJihegwDIDf/fx/gA==,type:str]
    SECRET_SOCIAL_DOMAIN: ENC[AES256_GCM,data:wc6difMLy7FhXGQy,iv:NPhjw/u5G3oAz6l/3qHVP8bCG9ri0Fa57GrXuDeztno=,tag:HxAi1AHkWJxg6UX87IQ30A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:bglxU+3puapxyLDONg==,iv:06fDzWedLlq/yvIRi0K4rpm0BOPArJC3x7hvCbbTLKI=,tag:QRSDRymUMXqtokhID1tGPQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Vi/G4JWodv6EiU3eCjt+45GxviL4w2JXk9u11oa2wofoyEpP,iv:ciOGsMmpu/dkf7Scww5KAeJlhRCs8/3Y6jVPCb/O3xY=,tag:sto4rPJSHncIem4Z0m/IUw==,type:str]
    SECRET_CLOUDFLARE_ACCOUNT_ID: ENC[AES256_GCM,data:lxSfe6q5l25a1ZgFxxuFYdTPcySC+YOymdSkaH5tSCk=,iv:gZX+WTNvNbPkyl7Bj/WfSM8WxpBoYkPVI6swNIw64p0=,tag:s5zlatl4zdahNba6QfWlSg==,type:str]
    SVC_BLOCKY_ADDR: ENC[AES256_GCM,data:2EQA7eQ5+r0SakPi,iv:a02gT6QqOieIeGA/E97wCM4aQSDyjXyPggbqPHCSAjQ=,tag:ecX9SfsG14aKZvObK/dwGg==,type:str]
    SVC_INGRESS_INTERNAL_ADDR: ENC[AES256_GCM,data:84fQIidtBPWBOd/4Ylc=,iv:MukyBP3Q/Jq7lKck9Jm+NhA23mP/M7SBO9vIm6SqvbQ=,tag:d2FLzIk5klzEqkN+YDRRhQ==,type:str]
    SVC_INGRESS_EXTERNAL_ADDR: ENC[AES256_GCM,data:kyhgRHvo0/up1CM+R/A=,iv:4CzYerHKzBPoDUscV2KV+5LChWjDlTkZwogE+qTM4Ws=,tag:o2EUTXbbsbYzIB3T0r73wA==,type:str]
    SVC_NUT_ADDR: ENC[AES256_GCM,data:x7Dz9R+qCUiT9BFcTs0=,iv:goHkskknFtyBwexAnmTMmBdMIYiHkEiBrCztJ3EQDnk=,tag:G5i+LaMFEBw3Po8/ze4ZKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1kmnhp30e40u4q54znn8ysz3atvee5k4q9r585y8mzxz9xuuxm37spk5w4w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQ0pCT1plMm1jc2l3Qll3
            bkdYOTd5b05OZ0lKOFBWQjZJQ0pXbEZremtRCjdONkR0ZVdJYTVxSTI4dmxad2sy
            aE5mL29FdkxhS1A4SU9lMHJYdGdaeU0KLS0tIDdOVDBST1hoOGNySldjam8xWHIx
            V1pMb3FiaEQ2cFczZjVmcmMwWS9LUTQKMB3OlhXDulA5Uc93Hp8Q704R+BMHnVcB
            S7ZQ1sjvKLWsXrpWvGntme8HCqFEHnOl3blKUJvlfSPgLHssJ8v9mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-21T22:26:59Z"
    mac: ENC[AES256_GCM,data:JcXq4EIYNSFjJ7kj07c/YnXpAJsP3DJr4KHHZQS8sGVb5u0sMSA8HCZW1NzzMW1b0+ujm6bp4WNycqaYI6DdKudTU1X+g44Bfk7wC95KpWV5u4+H1CemydTRlEQkrnv2fURKi3OhRn+G6dx0xZhzmD6JgqlzUaC6Hrp8tpnIjNU=,iv:sQv2IL1aQfdIGlxU1QeiMjIIK4633Zpih/mGAR5iM64=,tag:ARWhjNWpeIgqCFsgqNS4Gg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
